; Maximum allowed size for uploaded files.
upload_max_filesize = 25M

; Must be greater than or equal to upload_max_filesize
post_max_size = 26M

; Memory limit
memory_limit = 256M

; Maximum time in seconds a script is allowed to run
max_execution_time = 300

; Maximum time in seconds a script is allowed to parse input data
max_input_time = 300

; Display errors
display_errors = On
error_reporting = E_ALL 